[package]
name = "d7020e_lab3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# symex_lib = { git = "https://github.com/norlen/symex/crates/symex_lib", version = "1.0" }
# valid_derive = { git = "https://github.com/norlen/symex/crates/valid_derive", version = "1.0" }

symex = { git = "https://github.com/norlen/symex" }
